# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    document_validators.active_validators:
        - de
        - es
        - fr
        - it
        - pl
        - lt
        - uk
    document_validators.default.document_types:
        - { type: passport }
        - { type: identity_card }
        - { type: residence_permit }
    document_validators.default.date_format: 'Y-m-d'
    document_validators.default.request_limit: 
        max_attempts: 2
        max_workdays: 5
        workdays: [ Mon, Tue, Wed, Thu, Fri ] 
    document_validators.default.validity_period:
        year: 5
        document_types: [ passport, identity_card, residence_permit ]
    document_validators.default.weekday:
        days: [ Mon, Tue, Wed, Thu, Fri ] 
    document_validators.default.length: { length: 8 }

    document_validators.de:
        document_types: '%document_validators.default.document_types%'
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            - { year: 5, document_types: [ passport, identity_card, residence_permit ], till: '2009-12-31' }
            - { year: 10, document_types: [ identity_card ], from: '2010-01-01' }
        workdays:
            - '%document_validators.default.weekday%'
        lengths:
            - '%document_validators.default.length%'

    document_validators.es:
        document_types: '%document_validators.default.document_types%'
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            - { year: 5, document_types: [ identity_card, residence_permit ] }
            - { year: 5, document_types: [ passport ], till: '2013-02-13' }
            - { year: 15, document_types: [ passport ], from: '2013-02-14' }
        workdays:
            - '%document_validators.default.weekday%'
        lengths:
            - '%document_validators.default.length%'
        blacklists:
            - { document_types: [ passport ], min: '50001111', max: '50009999' }

    document_validators.fr:
        document_types:
            - { type: passport }
            - { type: identity_card }
            - { type: residence_permit }
            - { type: drivers_license }
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            -  { year: 5, document_types: [ passport, identity_card, residence_permit, drivers_license ] }
        workdays:
            - '%document_validators.default.weekday%'
        lengths:
            - '%document_validators.default.length%'

    document_validators.pl:
        document_types:
            - { type: passport }
            - { type: identity_card }
            - { type: residence_permit, from: '2015-06-01' }
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            - '%document_validators.default.validity_period%'
            - { year: 10, document_types: [ residence_permit ], from: '2015-06-01' }
        workdays:
            - '%document_validators.default.weekday%'
        lengths:
            - { length: 8, document_types: [ passport, residence_permit ] }
            - { length: 8, document_types: [ identity_card ], till: '2018-08-31' }
            - { length: 10, document_types: [ identity_card ], from: '2018-09-01' }

    document_validators.it:
        document_types: '%document_validators.default.document_types%'
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            - '%document_validators.default.validity_period%'
        workdays:
            - '%document_validators.default.weekday%'
            - { days: [ Sat ], from: '2019-01-01', till: '2019-01-31' }
        lengths:
            - '%document_validators.default.length%'

    document_validators.lt:
        document_types: '%document_validators.default.document_types%'
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            - '%document_validators.default.validity_period%'
        workdays:
            - '%document_validators.default.weekday%'
        lengths:
            - '%document_validators.default.length%'

    document_validators.uk:
        document_types:
            - { type: passport, from: '2019-01-01' }
        date_format: '%document_validators.default.date_format%'
        request_limit: '%document_validators.default.request_limit%'
        validity_periods:
            - '%document_validators.default.validity_period%'
        workdays:
            - '%document_validators.default.weekday%'
            - { days: [ Sat ], from: '2019-01-01', till: '2019-01-31' }
        lengths:
            - '%document_validators.default.length%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\TestController:
        arguments:
            $validator: '@app.document_validator_manager'

    app.storage.array_storage:
        class: App\Storage\ArrayStorage
        shared: true

    app.document_validator_manager:
        class: App\Document\Validator\DocumentValidatorManager

    App\Command\IdentificationRequestProcessCommand:
        arguments:
            $storage: '@app.storage.array_storage' 
            $documentValidators: '@app.document_validator_manager'